### ISSUE TITLE
Different days calculation in desktop & mobile apps

### ISSUE THREAD

**Issue by caznaran** [efyasar/world-cup-prediction-game#5]
In the desktop version the calculation of days until World Cup is different from the mobile version

Desktop version
![image](https://user-images.githubusercontent.com/65054557/202943468-469b5331-9c30-4572-9914-aedb19bd8109.png)

Mobile version
![image](https://user-images.githubusercontent.com/65054557/202943660-ee1be5fd-0b03-4d42-99ce-e1c132f2ebd0.png)

**Comment by efyasar** [comment]
Hello,
Please update your solution with latest version.
[How to update solution](https://github.com/efyasar/football-world-championship-prediction-game/wiki/How-to-Update-the-app) 

[This issue](https://github.com/efyasar/football-world-championship-prediction-game/issues/2) fixed with latest version.
